server:
  port: 8090
  servlet:
    context-path: /medicalClinic
application:
  title: medical clinic
  version: 1.0.0SNAPSHOT

# DATASOURCE
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clinical_db
    username: root
    password: root

## POOL DE CONECCIONES
    hikari:
      connection-timeout: 20000
      maximun-pool-size: 5

## JPA
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true